name: Sync Price (daily)
on:
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm install node-fetch@2

      - name: Run sync script
        env:
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          BRANCH: ${{ secrets.BRANCH || 'main' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTERNAL_API_URL: ${{ secrets.EXTERNAL_API_URL }}
        run: node scripts/sync-from-api.js
